name: news_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1


  cupertino_icons: ^1.0.2
  http: ^1.2.0
  google_fonts: 6.1.0
  cached_network_image: ^3.3.1
  provider: ^6.1.2
  animated_custom_dropdown: ^3.0.0
  url_launcher: ^6.2.5
  timeago: ^3.1.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  flutter_screenutil: ^5.9.0
  readmore: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  image_path: "assets/images/logo.png"
  android: "ic_launcher"
  ios: true


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
  generate: true


  assets:
    - assets/images/
    - assets/icons/

